# Generated by Django 3.0.6 on 2020-06-07 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='line_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default='', max_length=50, verbose_name='access token')),
                ('target_type', models.CharField(default='', max_length=5, verbose_name='target type')),
                ('target', models.CharField(default='', max_length=50, verbose_name='target')),
            ],
        ),
    ]
