# Generated by Django 3.0.6 on 2020-06-07 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_line_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='line_user',
            name='target_type',
            field=models.CharField(default='', max_length=5, verbose_name='target type'),
        ),
    ]
