# Generated by Django 3.0.6 on 2020-06-07 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_line_user_target_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='line_user',
            name='target',
            field=models.CharField(default='', max_length=50, verbose_name='target'),
        ),
        migrations.AlterField(
            model_name='line_user',
            name='token',
            field=models.CharField(default='', max_length=50, verbose_name='access token'),
        ),
    ]
